name: paperPlot-CI

on:
   push:
     branches: [main]
     paths-ignore:
        - '*.md'
        - 'README*'
        - 'LICENSE'
   pull_request:
     branches: [main]
     paths-ignore:
        - '*.md'
        - 'README*'
        - 'LICENSE'

jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install formatting dependencies
        run: |
          pip install black
          pip install isort
          pip install codespell
      - name: Formatting and sorting import
        run: |
          source .github/linters/formatting.sh
          format paperPlot true
          format tests true
          codespell
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install -r requirements.txt
      - name: Test
        run: |
          pytest -v 
